;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		crux-move-beginning-of-line
		indent-for-tab-command
		indent-rigidly
		))

(setq mc/cmds-to-run-once
      '(
		dumb-jump-go-other-window
		easy-kill
		end-of-buffer
		eval-buffer
		forward-sentence
		helm-projectile-switch-project
		ignore
		jn/clean-up-buffer
		js3-insert-and-indent
		js3-mode-show-node
		mac-mwheel-scroll
		magit-status
		mouse-appearance-menu
		mouse-set-region
		my-insert-tab-char
		suspend-frame
		text-scale-decrease
		whitespace-mode
		))
